<?php 
return [
    // start
    "hasi1" => "Special offers on computer products",
    "hasi2" => "Discover our exclusive offers on computers, software, and more.",
    "katalogoBotoia" => "View catalog",
    "eskaintzak" => "Offers",
    "oferta1" => "High-performance computer with HD display, Intel Core i7 processor, and 8 GB of RAM.",
    "oferta2" => "Yearly subscription including Word, Excel, PowerPoint, and more.",

    // our information
    "infor" => "Our information",
    "deskribapena" => "We're a company made up of three students from the Multi-Platform Application Development degree. We have created this company to sell new and renovated products, and to do so, we have created this website with options to buy you and make you a customer. If you have any doubts, here we are!ectives",

    // catalog
    "bilatzailea" => "Search product...",
    "bilatu" => "Search",
    "katergoria" => "Category:",
    "dena" => "All",
    "marka" => "Brand:",
    "markaIdatzi" => "write brand",
    "prezioa" => "Price:",
    "prezioMax" => "Price:",
    "balorazioa" => "Ratings:",
    "balorazioDenak" => "All",
    "filtratu" => "Filter",
    "almazena" => "Catalog from our warehouse",
    "prozesadorea" => "Processors",
    "txartGrafikoa" => "Graphics Card",
    "plaka" => "Motherboard",
    "disko" => "Hard Drive",
    "ram" => "RAM Memory",
    "sagua" => "Mice",
    "aurikular" => "Headphones",
    "teklatua" => "Keyboards",
    "pantaila" => "Displays",
    "portatila" => "Laptops",
    "saskiraGehitu" => "Add to Cart",

    // News
    "HasDat" => "Start date:",
    "AmaiDat" => "End date:",
    "Data" => "Date:",
    "aurr" => "Upcoming",
    "lehen" => "Previous",
    "Berri" => "Tech News",
    "notizi1" => "Advancements in Artificial Intelligence for Customs",
    "notizi1desk" => "Significant advancements have been made in the field of Artificial Intelligence.",
    "notizi2" => "Unveiling the new smartphone model",
    "notizi2desk" => "The new smartphone from company X is introduced with innovative features.",
    "notizi3" => "Cybersecurity: How to protect your data without permissions?",
    "notizi3desk" => "Tips for safeguarding your data in the digital world.",
    "notizi4" => "Software Development: Agile methodologies",
    "notizi4desk" => "How software development has evolved with agile methodologies.",
    "notizi5" => "Benefits of Cloud Computing",
    "notizi5desk" => "Analyzing how the way data is stored in the cloud is changing.",
    "notizi6" => "New vulnerability found in agile systems",
    "notizi6desk" => "Researchers have discovered a new vulnerability in common agile systems.",
    "notizi7" => "Technological Trends to Watch in the Coming Year",
    "notizi7desk" => "The year 2024 will be marked by technological trends, according to the clock.",
    "notizi8" => "Python Programming: The Language of the Moment",
    "notizi8desk" => "Changes in how Python is used in various regulatory projects.",
    "notizi9" => "Introduction of the new version of the software",
    "notizi9desk" => "Company Y has introduced a new version of its excellent software.",
    "notizi10" => "Robotics: Advances in Industrial Automation",
    "notizi10desk" => "How robots are transforming manufacturing and industry.",
    "notizi11" => "Massive cyberattack affects global companies",
    "notizi11desk" => "A major cyberattack has impacted some companies with serious consequences.",
    "notizi12" => "Decline in Cryptocurrencies",
    "notizi12desk" => "Cryptocurrencies continue to gain popularity as an investment form.",
    "notizi13" => "Development of Mobile Applications",
    "notizi13desk" => "How mobile applications can succeed in the market.",
    "notizi14" => "Introduction of New Processor Versions",
    "notizi14desk" => "Announcement of new strengthened processor versions in the market.",
    "notizi15" => "Online Security: How to protect your accounts?",
    "notizi15desk" => "Tips for securing and maintaining your online accounts.",
    "notizi16" => "Artificial Intelligence in the Health Field",
    "notizi16desk" => "How Artificial Intelligence is being used in the healthcare field is explained.",
    "notizi17" => "Unveiling the new version of video games",
    "notizi17desk" => "The long-awaited Video Game X is finally available for players.",
    "notizi18" => "5G Technology: The Future of Communications",
    "notizi18desk" => "Exploring how 5G technology is changing communication and connections.",
    "notizi19" => "Cyberattack on government networks",
    "notizi19desk" => "A cyberattack affecting government networks has been announced with serious consequences.",
    "notizi20" => "Development of Open Source Software",
    "notizi20desk" => "The significance of open-source software in the industry.",
    "notizi21" => "New versions of 3D printing technology",
    "notizi21desk" => "Advancements in 3D printing open new opportunities in construction.",
    "notizi22" => "New versions of mobile operating systems",
    "notizi22desk" => "Manufacturers have updated versions of mobile operating systems.",
    "notizi23" => "Impact of Social Networks on Society",
    "notizi23desk" => "Social networks have a great impact on society and play a significant role in relationships.",
    "notizi24" => "Importance of Cyber Education",
    "notizi24desk" => "Cyber education has become crucial for staying in digital education and learning new technologies.",
    "notizi25" => "Introduction of a new IoT device",
    "notizi25desk" => "A new Internet of Things (IoT) device has been launched.",
    "notizi26" => "Search for online video games",
    "notizi26desk" => "In recent years, online video games have been enduring and have experienced continuous growth.",
    "notizi27" => "Blockchain and the possibilities of blockchains",
    "notizi27desk" => "Exploring the possibilities of blockchain technology being examined in various sectors.",
    "notizi28" => "Introduction of a new version of the operating system",
    "notizi28desk" => "The introduction of a new version is usually challenging but comes with significant improvements.",
    "notizi29" => "Artificial Intelligence in the health sector",
    "notizi29desk" => "How Artificial Intelligence is used for improvement and diagnostics in the health sector is explained.",
    "notizi30" => "Virtual Reality and Augmented Reality for the Future",
    "notizi30desk" => "Virtual reality and augmented reality technologies promise an exciting future.",
    "aukeraHizkuntza" => "es",
    
    // supplier form
    "hornitzaileak" => "Supplier Form",
    "telZen" => "Phone Number:",
    "izena" => "Name:",
    "nan" => "ID Number:", 
    "mota" => "Type of Supplier:",
    "op1" => "Company",
    "op2" => "Person",
    "helb" => "Address",
    "zerbitzua" => "Service or Product Offered",

    // payment gateway
    "titulo" => "Payment Form",
    "detalles" => "Credit Card Details",
    "nombre" => "Cardholder Name:",
    "tarjeta" => "Card Number:",
    "fecha" => "Expiration Date (MM/YY):",
    "cvv" => "CVV:",
    "pago" => "Make Payment",

    //data
    "NAN" => "DNI:",
    "izena" => "Name:",
    "korreo" => "Email:",
    "kontukorronte" => "Bank Account:",

    // header 
    "hasiera" => "Home",
    "gureInfo" => "Our Information",
    "katalogoa" => "Catalog",
    "notiziak" => "News",
    "hornitzaileka" => "Suppliers",
    "fav" => "Favorites",
    "saskia" => "Shopping Cart",
    "total" => "Total: 0.00€",
    "hustu" => "Empty Cart",
    "erosi" => "Make a purchase",
    "ezabatu" => "Delete",

    //hizkuntza
    "aldatu" => "change"
];
