<?php 
return [
    // inicio
    "hasi1" => "Ofertas especiales en productos informáticos",
    "hasi2" => "Descubre nuestras ofertas exclusivas en ordenadores, software y más.",
    "katalogoBotoia" => "Ver catálogo",
    "eskaintzak" => "Ofertas",
    "oferta1" => "Ordenador de alto rendimiento con pantalla HD, procesador Intel Core i7 y 8 GB de RAM.",
    "oferta2" => "Suscripción anual que incluye Word, Excel, PowerPoint y más.",

    // nuestra información
    "infor" => "Nuestra información",
    "deskribapena" => "Objetivos",

    // catálogo
    "bilatzailea" => "Buscar producto...",
    "bilatu" => "Buscar",
    "katergoria" => "Categoría:",
    "dena" => "Todo",
    "marka" => "Marca:",
    "markaIdatzi" => "escribir marca",
    "prezioa" => "Precio:",
    "prezioMax" => "Precio:",
    "balorazioa" => "Valoraciones:",
    "balorazioDenak" => "Todas",
    "filtratu" => "Filtrar",
    "almazena" => "Catálogo de nuestro almacén",
    "prozesadorea" => "Procesadores",
    "txartGrafikoa" => "Tarjeta Gráfica",
    "plaka" => "Placa Base",
    "disko" => "Disco Duro",
    "ram" => "Memoria RAM",
    "sagua" => "Ratones",
    "aurikular" => "Auriculares",
    "teklatua" => "Teclados",
    "pantaila" => "Pantallas",
    "portatila" => "Portátiles",
    "saskiraGehitu" => "Añadir al carrito",

    // Noticias
    "HasDat" => "Fecha de inicio:",
    "AmaiDat" => "Fecha de finalización:",
    "Data" => "Fecha:",
    "aurr" => "Próximas",
    "lehen" => "Anteriores",
    "Berri" => "Noticias informáticas",
    "notizi1" => "Avances en Inteligencia Artificial para Aranzel",
    "notizi1desk" => "Se han logrado avances significativos en el campo de la Inteligencia Artificial.",
    "notizi2" => "Presentación del nuevo modelo de smartphone",
    "notizi2desk" => "Se presenta el nuevo smartphone de la empresa X con características innovadoras.",
    "notizi3" => "Ciberseguridad: ¿Cómo proteger tus datos sin permisos?",
    "notizi3desk" => "Consejos para proteger tus datos en el mundo digital.",
    "notizi4" => "Desarrollo de software: Metodologías ágiles",
    "notizi4desk" => "Cómo ha evolucionado el desarrollo de software con las metodologías ágiles.",
    "notizi5" => "Beneficios de la computación en la nube",
    "notizi5desk" => "Análisis de cómo está cambiando la forma de almacenar datos en la nube.",
    "notizi6" => "Nueva vulnerabilidad encontrada en sistemas ágiles",
    "notizi6desk" => "Los investigadores han encontrado una nueva vulnerabilidad en los sistemas ágiles comunes.",
    "notizi7" => "Tendencias tecnológicas para el próximo año",
    "notizi7desk" => "El reloj para ver las tendencias tecnológicas que marcarán el año 2024.",
    "notizi8" => "Programación en Python: Lenguaje de moda",
    "notizi8desk" => "Cambios en cómo se utiliza Python en diversos proyectos regulativos.",
    "notizi9" => "Presentación de la nueva versión del software",
    "notizi9desk" => "La empresa Y ha lanzado una nueva versión de su excelente software.",
    "notizi10" => "Robótica: Avances en automatización industrial",
    "notizi10desk" => "Cómo los robots están transformando la fabricación y la industria.",
    "notizi11" => "Un ciberataque masivo afecta a empresas globales",
    "notizi11desk" => "Un gran ciberataque ha impactado a algunas empresas con graves consecuencias.",
    "notizi12" => "La caída de las criptomonedas",
    "notizi12desk" => "Las criptomonedas continúan ganando popularidad como forma de inversión.",
    "notizi13" => "Desarrollo de aplicaciones para dispositivos móviles",
    "notizi13desk" => "Cómo tener éxito en el mercado desarrollando aplicaciones móviles.",
    "notizi14" => "Presentación de nuevas versiones de procesadores",
    "notizi14desk" => "Se han anunciado nuevas versiones de procesadores fortalecidos en el mercado.",
    "notizi15" => "Seguridad en línea: ¿Cómo proteger tus cuentas?",
    "notizi15desk" => "Consejos para proteger y mantener seguras tus cuentas en línea.",
    "notizi16" => "Inteligencia Artificial en el campo de la salud",
    "notizi16desk" => "Cómo se está utilizando la Inteligencia Artificial en el ámbito de la salud.",
    "notizi17" => "Presentación de la nueva versión de videojuegos",
    "notizi17desk" => "Finalmente disponible el esperado Videojuego X para jugadores.",
    "notizi18" => "Tecnología 5G: El futuro de las comunicaciones",
    "notizi18desk" => "Explorando cómo la tecnología 5G está cambiando la comunicación y las conexiones.",
    "notizi19" => "Ataque cibernético en redes gubernamentales",
    "notizi19desk" => "Se ha anunciado un ataque cibernético que afectará a las redes gubernamentales con graves consecuencias.",
    "notizi20" => "Desarrollo de software de código abierto",
    "notizi20desk" => "La importancia del software de código abierto en la industria.",
    "notizi21" => "Nuevas versiones de tecnología de impresión 3D",
    "notizi21desk" => "Los avances en la impresión 3D abren nuevas oportunidades en la construcción.",
    "notizi22" => "Nuevas versiones de sistemas operativos móviles",
    "notizi22desk" => "Los fabricantes han actualizado las versiones de los sistemas operativos móviles.",
    "notizi23" => "Impacto de las redes sociales en la sociedad",
    "notizi23desk" => "Las redes sociales tienen un gran impacto en la sociedad y desempeñan un papel importante en las relaciones.",
    "notizi24" => "Importancia de la educación cibernética",
    "notizi24desk" => "La cibereducación se ha vuelto crucial para mantenerse en la educación digital y aprender nuevas tecnologías.",
    "notizi25" => "Presentación de un nuevo dispositivo IoT",
    "notizi25desk" => "Un nuevo dispositivo IoT (Internet de las cosas) ha sido lanzado al mercado.",
    "notizi26" => "Búsqueda de videojuegos en línea",
    "notizi26desk" => "En los últimos años, los videojuegos en línea han sido duraderos y han experimentado un crecimiento continuo.",
    "notizi27" => "Blockchain y las posibilidades de las cadenas de bloques",
    "notizi27desk" => "Explorando las posibilidades de la tecnología de cadenas de bloques en diferentes sectores.",
    "notizi28" => "Presentación de una nueva versión del sistema operativo",
    "notizi28desk" => "La introducción de una nueva versión suele ser desafiante, pero con mejoras significativas.",
    "notizi29" => "Inteligencia Artificial en el campo de la salud",
    "notizi29desk" => "Cómo se utiliza la Inteligencia Artificial para mejorar el diagnóstico y la atención médica.",
    "notizi30" => "Realidad virtual y aumentada para el futuro",
    "notizi30desk" => "Las tecnologías de realidad virtual y aumentada prometen un futuro emocionante.",
    "aukeraHizkuntza" => "es",

    // formulario del proveedor
    "hornitzaileak" => "Formulario de proveedores",
    "telZen" => "Número de teléfono:",
    "izena" => "Nombre:",
    "nan" => "DNI:", 
    "mota" => "Tipo de proveedor:",
    "op1" => "Empresa",
    "op2" => "Persona",
    "helb" => "Dirección",
    "zerbitzua" => "Servicio o producto ofrecido",

    // pasarela de pago
    "titulo" => "Formulario de Pago",
    "detalles" => "Detalles de Tarjeta de Crédito",
    "nombre" => "Nombre del Titular de la Tarjeta:",
    "tarjeta" => "Número de Tarjeta:",
    "fecha" => "Fecha de Caducidad (MM/YY):",
    "cvv" => "CVV:",
    "pago" => "Realizar Pago",

    // encabezado 
    "hasiera" => "Inicio",
    "gureInfo" => "Nuestra información",
    "katalogoa" => "Catálogo",
    "notiziak" => "Noticias",
    "hornitzaileka" => "Proveedores",
    "fav" => "Favoritos",
    "saskia" => "Carrito de compra",
    "total" => "Total: 0.00€",
    "hustu" => "Vaciar carrito",
    "erosi" => "Realizar compra",

    //hizkuntza
    "aldatu" => "cambiar"
];
