<?php 
return[
    // hasiera
    "hasi1" => "Produktu informatikoen eskaintza bereziak",
    "hasi2" => "Ezagutu gure eskaintza esklusiboak ordenagailuetan, softwaretan eta gehiagotan.",
    "katalogoBotoia" => "Ikusi katalogoa",
    "eskaintzak" => "Eskaintzak",
    "oferta1" => "Errendimendu handiko ordenagailua HD pantailarekin, Intel Core i7 prozesadorea eta RAMeko 8 GB.",
    "oferta2" => "Word, Excel, PowerPoint eta gehiago barne hartzen dituen urtebeteko harpidetza.",

    //gure informazioa
    "infor" => "Gure informazioa",
    "deskribapena" => "Plataforma Anitzeko Aplikazioen Garapena graduko hiru ikaslek osatutako enpresa bat gara. Produktu berriak eta berrituak saltzeko sortu dugu enpresa hau, eta, horretarako, webgune hau sortu dugu, zu erosteko eta bezero egiteko aukerekin. Zalantzarik baduzue, hemen gaude!",

    //katalogoa
    "bilatzailea" => "Bilatu produktua...",
    "bilatu" => "Bilatu",
    "katergoria" => "Kategoria:",
    "dena" => "Dena",
    "marka" => "Marka:",
    "markaIdatzi" => "idatzi marka",
    "prezioa" => "Prezioa:",
    "prezioMax" => "Prezioa:",
    "balorazioa" => "Balorazioak:",
    "balorazioDenak" => "Denak",
    "filtratu" => "Filtratu",
    "almazena" => "Gure almazenaren katalogoa",
    "prozesadorea" => "Prozesadoreak",
    "txartGrafikoa" => "Txartel Grafikoa",
    "plaka" => "Plaka Basea",
    "disko" => "Disko Gogorra",
    "ram" => "RAM Memoria",
    "sagua" => "Sagua",
    "aurikular" => "Aurikullarrak",
    "teklatua" => "Teklatuak",
    "pantaila" => "Pantaila",
    "portatila" => "Portatila",
    "saskiraGehitu" => "Sakira gehitu",

    //Notiziak
    "HasDat" => "Hasierako data:",
    "AmaiDat" => "Amaierako data:",
    "Data" => "Data:",
    "aurr" => "aurreragokoak",
    "lehen" => "lehenagokoak",
    "Berri" => "Berri informatikoak",
    "notizi1" => "Ikerketak Aranzelako Adimen Artifizialean",
    "notizi1desk" => "Adimen Artifizialearen alorrean egindako aurrerapen handiak lortu dira.",
    "notizi2" => "Azken smartphonearen eredua aurkeztu",
    "notizi2desk" => "X enpresa duen smartphone berria aurkezten da ezaugarri berritzaileekin.",
    "notizi3" => "Ziber-segurtasuna: Zein duzu zure informazioa baimenik gabe?",
    "notizi3desk" => "Zure datuak zaindu ahal izateko aholkuak mundu digitalian.",
    "notizi4" => "Software garapena: Metodologia agileak",
    "notizi4desk" => "Metodologia agilak nola garatu den aldatzen ari da softwarea.",
    "notizi5" => "Hodei konputazioaren onurak",
    "notizi5desk" => "Nubean datuak gordetzeko modua nola aldatzen ari den azterketa.",
    "notizi6" => "Sistema eragileetan aurkitutako hankamen berria",
    "notizi6desk" => "Ikerlariok oso hankamena aurkitu dute sistema eragile ohikoetan.",
    "notizi7" => "Teknologikoari begirako tendentziak hurrengo urtean",
    "notizi7desk" => "2024. urtea markatuko duten teknologia tendentziak ikusteko erlojua.",
    "notizi8" => "Python programazioa: Modako lengoaia",
    "notizi8desk" => "Python proiektatzen dutenaren hainbat proiektu arautzaileetan aldatu izan da.",
    "notizi9" => "Softwarearen bertsio berriaren aurkezpena",
    "notizi9desk" => "Y enpresak bere software bikainaren bertsio berri bat aurkeztu du.",
    "notizi10" => "Robotika: Industri automatizazioaren aurrerapenak",
    "notizi10desk" => "Nola eraldatzen ari dira robotek fabrikazioa eta industriaren alorrean.",
    "notizi11" => "Ziber-eraso masiboa enpresa globalak eragiten ditu",
    "notizi11desk" => "Ziber-eraso handia enpresa batzuei eragin die, ondorio larriekin.",
    "notizi12" => "Kripto-monetak beherakoa",
    "notizi12desk" => "Kripto-monetak inbertsio moduko gisa popularitatea lortzen jarraitzen dute.",
    "notizi13" => "Mugikorretarako aplikazioen garapena.",
    "notizi13desk" => "Aplikazio mugikorrak egiten nola arrakasta izan dezakeen merkatuan.",
    "notizi14" => "Prozesagailuak: Aurreko bertsioak",
    "notizi14desk" => "Merkatuko prozesagailu sendotzen diren bertsioak iragarriak izan dira.",
    "notizi15" => "Online segurtasuna: Zein da zure kontuak babestu behar dituzun?",
    "notizi15desk" => "Zure online kontuak babesteko eta zaindu beharreko aholkuak.",
    "notizi16" => "Osasun arloko Adimen Artifiziala",
    "notizi16desk" => "Adimen Artifiziala nola erabiltzen ari den osasun arloan azaltzen da.",
    "notizi17" => "Videojokoen bertsio berriaren aurkezpena.",
    "notizi17desk" => "Espero den Videojoko X jokalarientzako azkenik eskuragarri da.",
    "notizi18" => "5G teknologia: Komunikazioen etorkizuna",
    "notizi18desk" => "Nola 5G teknologia eta harremanen eremua aldatzen ari den aztertzen da.",
    "notizi19" => "Ziber-erasoa gobernu sareetan",
    "notizi19desk" => "Gobernu sareetan eragingo duen ziber-erasoa jakinarazi da eta ondorio larriekin.",
    "notizi20" => "Zabal-kodeko softwarearen garapena",
    "notizi20desk" => "Zabal-kodeko softwarea zenbaki handiko garrantzia dauka industriaren alorrean.",
    "notizi21" => "3D inprimaketa teknologikoaren bertsio berrienak",
    "notizi21desk" => "3D inprimaketan lortutako aurrerapenek eraikuntzan aukera berriak irekitzen dituzte.",
    "notizi22" => "Mugikorretarako sistema eragileen bertsio berriak",
    "notizi22desk" => "Fabrikatzaileek beren mugikorretarako sistema eragileen bertsioak berritu dituzte.",
    "notizi23" => "Sare sozialen eragina gizartean",
    "notizi23desk" => "Sare sozialak gizartearekin duen eragina kontu handia dute eta harremanean jarduten dute.",
    "notizi24" => "Ziber-hezkuntzaren garrantzia",
    "notizi24desk" => "Hezkuntza digitalean mantentzeko eta teknologia berriak ikasteko, ziber-hezkuntza oso garrantzitsua bihurtu da.",
    "notizi25" => "IoT dispositivo berri bat aurkezpena",
    "notizi25desk" => "IoT (Interneteko gauzaen Interneteko gauzaen) dispositivo berri bat dator martxan.",
    "notizi26" => "Online bideo-jokoen bilaketa",
    "notizi26desk" => "Azken urteetan bideo-jokoak iraunkorrak izan dira eta hazkuntza etengabea izan dute.",
    "notizi27" => "Blockchain eta bloke-kateen aukerak",
    "notizi27desk" => "Bloke-kate teknologia sektore ezberdinetan aztertzen ari den bloke-kate teknologiaren aukerak.",
    "notizi28" => "Sistema eragileen bertsio berri bat aurkezpena",
    "notizi28desk" => "Bertsio berri bat zaila dakar eta hobekuntza handiak izango ditu.",
    "notizi29" => "Adimen Artifiziala osasun alorrean",
    "notizi29desk" => "Nola erabilten den Adimen Artifiziala osasun arloan hobekuntza eta diagnostikoa bideratzeko azaltzen da.",
    "notizi30" => "Errealitate birtuala eta areagatik etorkizuna",
    "notizi30desk" => "Errealitate birtuala eta areagako teknologiak etorkizun emozionagarria hurbiltzen duten teknologiak promesatzen dute.",
    "aukeraHizkuntza" => "eus",

    //hornitzaileform

    "hornitzaileak" => "Hornitzaile formularioa",
    "telZen" => "Telefono zenbakia:",
    "izena" => "Izena:",
    "nan" => "NAN:", 
    "mota" => "Hornitzaile mota:",
    "op1" => "Enpresa",
    "op2" => "Pertsona",
    "helb" => "Helbidea",
    "zerbitzua" => "Eskaintzen den zerbitzua edo produktua",

    //pasarela de pago
    "titulo" => "Ordainketa Formularioa",
    "detalles" => "Kreditu Txartelaren Xehetasunak",
    "nombre" => "Txartelaren Jabearen Izena:",
    "tarjeta" => "Txartel Zenbakia:",
    "fecha" => "Iraungitze Data (HH/IH):",
    "cvv" => "CVV:",
    "pago" => "Ordainketa Egin",

    //datuak
    "NAN" => "NAN:",
    "izena" => "Izena:",
    "korreo" => "Korreoa:",
    "kontukorronte" => "Kontu Korrontea:",

    //header 
    "hasiera" => "Hasiera",
    "gureInfo" => "Gure informazioa",
    "katalogoa" => "Katalogoa",
    "notiziak" => "Notiziak",
    "hornitzaileka" => "Hornitzaileak",
    "fav" => "Gustokoenak",
    "saskia" => "Erosketa saskia",
    "total" => "Totala: 0.00€",
    "hustu" => "Hustu saskia",
    "erosi" => "Erosketa egin",
    "ezabatu" => "Ezabatu",

    //hizkuntza
    "aldatu" => "aldatu"
];
